### ▪︎ NumPy Import → `import numpy as np`

### ▪︎ ndarray 
넘파이에서 제공하는 다차원 배열을 다루기 위한 클래스

In [1]:
import numpy as np

arr = np.array([1,2,3,4]) # type ndarray type
arr10 = arr*10

print(arr10)

[10 20 30 40]


(설명) python list type인 [1,2,3,4]를 numpy의 ndarray type으로 바꿔줌.
(추가) numpy가 c언어로 개발되어 있어서 python 보다 속도가 빠름

## ▪︎ 2차원 데이터 열 단위 한번에 접근하기 
파이썬 같은 경우 2차원 리스트로 정의된 데이터에 접근할 때, 인덱싱으로만으로 한 번에 열 단위 접근이 어렵지만, ndarray 타입은 가능하다.

In [3]:
import numpy as np

price = [
    [100, 80, 70, 90],
    [120, 110, 100, 110]
]

arr2 = np.array(price) # type numpy.ndarray

<class 'numpy.ndarray'>


### (1) 행 단위로 인덱싱 하기

In [7]:
arr2[0]

array([120, 110, 100, 110])

In [8]:
arr2[1]

array([120, 110, 100, 110])

### (2) 행 → 열 순서로 접근

In [10]:
arr2[0][0]

np.int64(100)

In [11]:
arr2[0,0]

np.int64(100)

### (3) 열 단위 접근하기

In [12]:
arr2[:, 0] # 모든 행에 대해 0번째 열 선택

array([100, 120])

In [14]:
arr2[:, 1]

array([ 80, 110])